name: 'Run with Chrome Unstable'
description: 'Execute command after installing Google Chrome Unstable'
inputs:
  command:
    description: 'what command to execute?'
    required: true
    default: 'node index.js'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
